[package]
name = "bitwarden_rs"
version = "1.0.0"
authors = ["Daniel García <dani-garcia@users.noreply.github.com>"]
edition = "2018"

repository = "https://github.com/dani-garcia/bitwarden_rs"
readme = "README.md"
license = "GPL-3.0-only"
publish = false
build = "build.rs"

[features]
# default = ["sqlite"]
# Empty to keep compatibility, prefer to set USE_SYSLOG=true
enable_syslog = []
mysql = ["diesel/mysql", "diesel_migrations/mysql"]
postgresql = ["diesel/postgres", "diesel_migrations/postgres"]
sqlite = ["diesel/sqlite", "diesel_migrations/sqlite", "libsqlite3-sys"]

[target."cfg(not(windows))".dependencies]
syslog = "4.0.1"

[dependencies]
# Web framework for nightly with a focus on ease-of-use, expressibility, and speed.
rocket = { version = "0.5.0-dev", features = ["tls"], default-features = false }
rocket_contrib = "0.5.0-dev"

# Async futures
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["rt-threaded", "blocking", "fs", "io-util"] }

# HTTP client
reqwest = { version = "0.10.6", features = ["stream", "json"] }
bytes = "0.5.4"

# multipart/form-data support
multipart = { version = "0.17.0", features = ["server"], default-features = false }

# WebSockets library
ws = "0.9.1"

# MessagePack library
rmpv = "0.4.4"

# Concurrent hashmap implementation
chashmap = "2.2.2"

# A generic serialization/deserialization framework
serde = "1.0.112"
serde_derive = "1.0.112"
serde_json = "1.0.55"

# Logging
log = "0.4.8"
fern = { version = "0.6.0", features = ["syslog-4"] }

# A safe, extensible ORM and Query builder
diesel = { version = "1.4.5", features = [ "chrono", "r2d2"] }
diesel_migrations = "1.4.0"

# Bundled SQLite
libsqlite3-sys = { version = "0.17.3", features = ["bundled"], optional = true }

# Crypto library
ring = "0.16.14"

# UUID generation
uuid = { version = "0.8.1", features = ["v4"] }

# Date and time librar for Rust
chrono = "0.4.11"

# TOTP library
oath = "0.10.2"

# Data encoding library
data-encoding = "2.2.1"

# JWT library
jsonwebtoken = "7.1.1"

# U2F library
u2f = "0.2.0"

# Yubico Library
yubico = { version = "0.9.0", features = ["online-tokio"], default-features = false }

# A `dotenv` implementation for Rust
dotenv = { version = "0.15.0", default-features = false }

# Lazy initialization
once_cell = "1.4.0"

# Numerical libraries
num-traits = "0.2.12"
num-derive = "0.3.0"

# Email libraries
lettre = { version = "0.10.0-alpha.1", features = ["smtp-transport", "builder", "serde", "native-tls"], default-features = false }
native-tls = "0.2.4"

# Template library
handlebars = { version = "3.1.0", features = ["dir_source"] }

# For favicon extraction from main website
soup = "0.5.0"
regex = "1.3.9"
data-url = "0.1.0"

# Used by U2F, JWT and Postgres
openssl = "0.10.29"

# URL encoding library
percent-encoding = "2.1.0"
# Punycode conversion
idna = "0.2.0"

# CLI argument parsing
structopt = "0.3.14"

# Logging panics to logfile instead stderr only
backtrace = "0.3.49"

ctrlc = { version = "3.1.4", features = ["termination"] }

[patch.crates-io]
# Use newest ring
rocket = { git = 'https://github.com/SergioBenitez/Rocket', rev = '4928e35ec5c4b9242f50d644282d9896d0160a10' }
rocket_contrib = { git = 'https://github.com/SergioBenitez/Rocket', rev = '4928e35ec5c4b9242f50d644282d9896d0160a10' }

# For favicon extraction from main website
data-url = { git = 'https://github.com/servo/rust-url', package="data-url", rev = '7f1bd6ce1c2fde599a757302a843a60e714c5f72' }
